export const AUTHENTICATION_KEY = "FILM_IS_JWT_TOKEN";

export const CURRENT_CINEMA_ID = "CURRENT_CINEMA_ID";
export const CURRENT_ROOM_ID = "CURRENT_ROOM_ID";
export const CURRENT_DATE = "CURRENT_DATE";
